travis:
  secure:
    BINSTAR_TOKEN: NOogPFv8CP3o7ReLsUqqETcalnr63miHglSTiRiAxelvl3Tf+P95kSHhxfsv3kxFhbmBu0YUK7i8NZ/cGX8LmSSPtx4sko6a6MxvSlpmI3wD+Z8TVuD0YPRkOfe1p/apnY0bvTAr/lUt/+ftoEboUjdO+rGVNsbSRdkVNaTekFLu6qcmomO4dGuaI0bpaeP9lTnI6IlY/j01VY1FpZiWbPDmBTFcr0xO6hoXCLgFilkMawC1j8Hw5splanRewy7T8Z79bU/wOycOLHnuGYOYLEKTHv+J1vfWOsK2MfFAfbbANTWehozHeVse0EH+dL5gd1GH4QwsUVRHEQBiO9QFjEGv63OrhAQrkG0WUtC4pKKDEy6fZp8yoyvBAwB2oMjkX4HTdq0a+Uk/KRQJwQHlZxUBYSRUkPATOwwMCP3ADCkA/IH6RVmGUFITFszyc7MPxYY2njqZCStAYWvE1c0C8Fx0d0uqUGSJ1NkQ9romKyAy76Y/70QdQHQT5RrQqb+1+lR0nk7No5ySuQFyKP1nvI9M6h5Jmo9fJMg6sM4/1+t/KAPPsA1zEtUKRIrWMfMWdvCcXYn+dMm1yprrytTDIPfZcj6M9lECpLugGo3Ep8Hgtv9mx92FVtYEbIXhb4KVUH+0gI3hjdFeCkzvRfPPdgqE+UVl139IBURjCse3TNA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
